config/routes.rb
Rails.application.routes.draw do
  resources :vehiculos
  resources :tipo_vehiculos
  resources :profiles, only: [:edit, :update]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'pages#index'

  get 'pages/login'

  get 'pages/bucar'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  def full_name

      self.first_name + " " + self.last_name

  end
end

app/models/tipo_vehiculo.rb
class TipoVehiculo < ActiveRecord::Base
    has_many :vehiculos
    def name
        des_tipo_vehiculo
    end
        
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
  
  
  enum role: [:user, :operator, :chef, :admin]

  after_initialize :set_default_role

  def set_default_role

    self.role ||= :user

  end
  

  def default_profile

    if self.profile.nil?
  
      profile = Profile.new
  
      profile.user = self
  
      profile.save
  
      self.save      
  
    end

  self.profile

  end
  
  
  def friendly_name

    if self.default_profile.first_name.nil?

      self.email

    else

      self.profile.full_name

    end

  end
  
  
end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
  belongs_to :tipo_vehiculo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def login
  end

  def bucar
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to root_url, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :born_at, :user_id)
    end
end

app/controllers/tipo_vehiculos_controller.rb
class TipoVehiculosController < ApplicationController
  before_action :set_tipo_vehiculo, only: [:show, :edit, :update, :destroy]

  # GET /tipo_vehiculos
  # GET /tipo_vehiculos.json
  def index
    @tipo_vehiculos = TipoVehiculo.all
  end

  # GET /tipo_vehiculos/1
  # GET /tipo_vehiculos/1.json
  def show
  end

  # GET /tipo_vehiculos/new
  def new
    @tipo_vehiculo = TipoVehiculo.new
  end

  # GET /tipo_vehiculos/1/edit
  def edit
  end

  # POST /tipo_vehiculos
  # POST /tipo_vehiculos.json
  def create
    @tipo_vehiculo = TipoVehiculo.new(tipo_vehiculo_params)

    respond_to do |format|
      if @tipo_vehiculo.save
        format.html { redirect_to @tipo_vehiculo, notice: 'Tipo vehiculo was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_vehiculo }
      else
        format.html { render :new }
        format.json { render json: @tipo_vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_vehiculos/1
  # PATCH/PUT /tipo_vehiculos/1.json
  def update
    respond_to do |format|
      if @tipo_vehiculo.update(tipo_vehiculo_params)
        format.html { redirect_to @tipo_vehiculo, notice: 'Tipo vehiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_vehiculo }
      else
        format.html { render :edit }
        format.json { render json: @tipo_vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_vehiculos/1
  # DELETE /tipo_vehiculos/1.json
  def destroy
    @tipo_vehiculo.destroy
    respond_to do |format|
      format.html { redirect_to tipo_vehiculos_url, notice: 'Tipo vehiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_vehiculo
      @tipo_vehiculo = TipoVehiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_vehiculo_params
      params.require(:tipo_vehiculo).permit(:des_tipo_vehiculo)
    end
end

app/controllers/vehiculos_controller.rb
class VehiculosController < ApplicationController
  before_action :set_vehiculo, only: [:show, :edit, :update, :destroy]

  # GET /vehiculos
  # GET /vehiculos.json
  def index
    @vehiculos = Vehiculo.all
  end

  # GET /vehiculos/1
  # GET /vehiculos/1.json
  def show
  end

  # GET /vehiculos/new
  def new
    @vehiculo = Vehiculo.new
  end

  # GET /vehiculos/1/edit
  def edit
  end

  # POST /vehiculos
  # POST /vehiculos.json
  def create
    @vehiculo = Vehiculo.new(vehiculo_params)

    respond_to do |format|
      if @vehiculo.save
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully created.' }
        format.json { render :show, status: :created, location: @vehiculo }
      else
        format.html { render :new }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehiculos/1
  # PATCH/PUT /vehiculos/1.json
  def update
    respond_to do |format|
      if @vehiculo.update(vehiculo_params)
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehiculo }
      else
        format.html { render :edit }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehiculos/1
  # DELETE /vehiculos/1.json
  def destroy
    @vehiculo.destroy
    respond_to do |format|
      format.html { redirect_to vehiculos_url, notice: 'Vehiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehiculo
      @vehiculo = Vehiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehiculo_params
      params.require(:vehiculo).permit(:modelo, :marca, :placa, :tipo_vehiculo_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tipo_vehiculos_helper.rb
module TipoVehiculosHelper
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/layouts/_autentication.html.erb
<p class="navbar-text navbar-right">

  <% if current_user %>

      Signed in as <%= link_to current_user.friendly_name, edit_profile_path(current_user.default_profile), class: "navbar-link" %>

      <%= " | " %>

      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-link" %>

  <% else %>

      <%= link_to "Sign in", new_user_session_path, class: "navbar-link" %>

  <% end %>

</p>

app/views/layouts/_menu.html.erb
<li><%= link_to "Home", pages_bucar_path  %></li>

<li><%= link_to "How it Work", pages_bucar_path  %></li>

<li><%= link_to "Testimonial", pages_bucar_path  %></li>

<li><%= link_to "Contact us", pages_bucar_path  %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "InstaParking" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <%= render 'layouts/autentication' %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">InstaParking</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render "layouts/menu" %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <%= render "layouts/menu" %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/internal.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "InstaParking" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <%= render 'layouts/autentication' %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">InstaParking</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/bucar.html.erb
<h1>Pages#bucar</h1>

<p>Find me in app/views/pages/bucar.html.erb</p>

app/views/pages/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->

  <ol class="carousel-indicators">

    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>

    <li data-target="#carousel-example-generic" data-slide-to="1"></li>

    <li data-target="#carousel-example-generic" data-slide-to="2"></li>

  </ol>

  <!-- Wrapper for slides -->

  <div class="carousel-inner" role="listbox">

    <div class="item active">

      <%= image_tag "pag1.jpg", html: { alt: "pag1" } %>

      <div class="carousel-caption">

        <h3>Buena Atención</h3>

        <p>Personal Capacitado</p>

      </div>

    </div>

    <div class="item">

      <%= image_tag "pag2.jpg", html: { alt: "pag2" } %>

      <div class="carousel-caption">

        <h3>Buen Espacio</h3>

        <p>Amplias Areas</p>

      </div>

    </div>

    <div class="item">

      <%= image_tag "pag3.jpg", html: { alt: "pag3" }%>

      <div class="carousel-caption">

        <h3>Orden de Ubicación</h3>

        <p>Ubicación a medida</p>

      </div>

    </div>

  </div>

  <!-- Controls -->

  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">

    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

    <span class="sr-only">Previous</span>

  </a>

  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">

    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

    <span class="sr-only">Next</span>

  </a>

</div>

app/views/pages/login.html.erb
<h1>Pages#login</h1>

<p>Find me in app/views/pages/login.html.erb</p>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :born_at, as: :date %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Born at</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.born_at %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show Profile', profile %></td>
        <td><%= link_to 'Edit Profile', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy Profile', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Born at:</strong>
  <%= @profile.born_at %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/tipo_vehiculos/_form.html.erb
<%= simple_form_for(@tipo_vehiculo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :des_tipo_vehiculo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tipo_vehiculos/edit.html.erb
<h1>Editing Tipo Vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_vehiculo %> |
<%= link_to 'Back', tipo_vehiculos_path %>

app/views/tipo_vehiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tipo Vehiculos</h1>

<table>
  <thead>
    <tr>
      <th>Des tipo vehiculo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_vehiculos.each do |tipo_vehiculo| %>
      <tr>
        <td><%= tipo_vehiculo.des_tipo_vehiculo %></td>
        <td><%= link_to 'Show', tipo_vehiculo %></td>
        <td><%= link_to 'Edit', edit_tipo_vehiculo_path(tipo_vehiculo) %></td>
        <td><%= link_to 'Destroy', tipo_vehiculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo vehiculo', new_tipo_vehiculo_path %>

app/views/tipo_vehiculos/new.html.erb
<h1>New Tipo Vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_vehiculos_path %>

app/views/tipo_vehiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Des tipo vehiculo:</strong>
  <%= @tipo_vehiculo.des_tipo_vehiculo %>
</p>

<%= link_to 'Edit', edit_tipo_vehiculo_path(@tipo_vehiculo) %> |
<%= link_to 'Back', tipo_vehiculos_path %>

app/views/vehiculos/_form.html.erb
<%= simple_form_for(@vehiculo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :modelo %>
    <%= f.input :marca %>
    <%= f.input :placa %>
    <%= f.association :tipo_vehiculo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vehiculos/edit.html.erb
<h1>Editing Vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehiculo %> |
<%= link_to 'Back', vehiculos_path %>

app/views/vehiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vehiculos</h1>

<table>
  <thead>
    <tr>
      <th>Modelo</th>
      <th>Marca</th>
      <th>Placa</th>
      <th>Tipo vehiculo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehiculos.each do |vehiculo| %>
      <tr>
        <td><%= vehiculo.modelo %></td>
        <td><%= vehiculo.marca %></td>
        <td><%= vehiculo.placa %></td>
        <td><%= vehiculo.tipo_vehiculo.des_tipo_vehiculo %></td>
        <td><%= link_to 'Show', vehiculo %></td>
        <td><%= link_to 'Edit', edit_vehiculo_path(vehiculo) %></td>
        <td><%= link_to 'Destroy', vehiculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehiculo', new_vehiculo_path %>

app/views/vehiculos/new.html.erb
<h1>New Vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Back', vehiculos_path %>

app/views/vehiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Modelo:</strong>
  <%= @vehiculo.modelo %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @vehiculo.marca %>
</p>

<p>
  <strong>Placa:</strong>
  <%= @vehiculo.placa %>
</p>

<p>
  <strong>Tipo vehiculo:</strong>
  <%= @vehiculo.tipo_vehiculo.des_tipo_vehiculo %>
</p>

<%= link_to 'Edit', edit_vehiculo_path(@vehiculo) %> |
<%= link_to 'Back', vehiculos_path %>